### ISSUE TITLE
Handle exit codes / build errors

### ISSUE THREAD

**Issue by ciarand** [go-godo/godo#23]
If [this](https://github.com/go-godo/godo/blob/master/tasks/Godofile.go#L38-L40) test function (reproduced below) fails at any point `godo` continues to return an exit code of 0, which is unhelpful for use in e.g. git hooks.

```go
	p.Task("test", func() {
		Run("go test")
	})
```

Can we add an acceptable error returning func type?

```go
	p.Task("test", func() error {
		return Run("go test")
	})
```

The expected result would be that if a function returned an error, the process would exit.

Calling `os.Exit` should be done at the outermost layer as much as possible because any `defer`'d functions are not guaranteed to be called if an `os.Exit` happens deeper in the call stack.

UPDATED: a previous version of this issue talked about the lint task (gofmt, go vet, golint) but the test one is simpler

**Comment by ciarand** [comment]
You are my hero :sparkles:

**Comment by ansel1** [comment]
the good command doesn't exit with the same code though.  Running the above sample with `godo test` would still result in a 0 exit code.
