### ISSUE TITLE
Namespace?

### ISSUE THREAD

**Issue by runemadsen** [go-godo/godo#29]
I just created a dead simple task:

```
p.Task("db:prepare", func() {
  fmt.Println("hello")
})
```

Running it logs this message:

`project Could not find project having namespace "db"`

I looked through the README and the tests, and I see no mention of namespaces. I can't really get a sense of what this means by looking at the code.

Ideas?

**Comment by mgutz** [comment]
Godo treats anything with a ":" as a namespace. Rename it as "db-prepare". Namespaces are reserved for including other tasks:

``` go
// could be from another package or file
func BuildTasks(p *Project) {
    p.Task("server", nil, func(c *Context) {
    })
}

func tasks(p *Project) {
    p.Use("build", BuildTasks)
}

func main() {
    Godo(tasks)
}
```

To run server task from BuildTasks

``` sh
godo build:server
```

**Comment by runemadsen** [comment]
Oh, awesome. Thanks!
