### ISSUE TITLE
Why not tasks/main.go

### ISSUE THREAD

**Issue by clouds56** [go-godo/godo#30]
In godo.v2, the document says that only Gododir/main.go will be read.
personally I don't like a directory call itself dir and a file called somefile.
If you don't like "tasks", maybe just godo/main.go would be fine. or you can use some option to switch which files used for godo task.

**Comment by mgutz** [comment]
There is no rhyme reason, it was an arbitrary choice. I could easily add `tasks/main.go`. There are currently 3 files that are searched for legacy reasons

https://github.com/go-godo/godo/blob/v2/cmd/godo/main.go#L50

**Comment by clouds56** [comment]
Yes, I modify the line and build godo.v2 myself, and it works.
Thank you.
