### ISSUE TITLE
why it took more than 10 seconds to build or rebuild the project

### ISSUE THREAD

**Issue by hankya** [go-godo/godo#37]
It took too long for the application to load

**Comment by mgutz** [comment]
Probably two things:

1) You are on Go 1.5+ which is slow to compile
2) Godo rebuilds all packages since Go isn't very smart about rebuliding packages external to your main package https://groups.google.com/forum/#!msg/golang-nuts/Z5uJf6mEF6E/K7yb6Xc5zQUJ

**Comment by hankya** [comment]
Ah, I see, the -a flag.
I noticed v2 kind of fixed this problem, thanks!
